backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - label: "Updates"
    name: updates
    folder: site/content/updates
    create: true
    extension: "md"
    fields:
      - {label: Date, name: date, widget: datetime}
      - {label: Draft, name: draft, widget: boolean}
      - {label: Title, name: title, widget: string}
      - {label: Thumb, name: thumb, widget: image, hint: '240 by 240px'}
      - {label: Post Image, name: postImg, widget: image, hint: '1440px wide'}
      - {label: Content Type, name: contentType, widget: select, options: ["work", "personal"]}
      - {label: Excerpt, name: listSummary, widget: markdown}
      - {label: Body, name: body, widget: markdown}
  - label: "Content Types"
    name: "contentTypes"
    files:
      - label: "News Links"
        name: "newsLinks"
        file: "site/data/news/links.yml"
        fields:
          - {label: Title, name: title, widget: hidden}
          - label: News Item
            name: newsListDisplay
            widget: list
            fields:
              - {label: Article Title, name: news, widget: string}
              - {label: Link, name: link, widget: string}
              - {label: Comment, name: comment, widget: string}
              - {label: Date, name: date, widget: datetime}
      - label: "Affinities Items"
        name: "affinitiesItems"
        file: "site/data/affinities/items.yml"
        fields:
          - {label: Title, name: title, widget: hidden}
          - label: Current Reading 
            name: reading 
            widget: list
            allow_add: false
            fields:
              - {label: Book Title, name: bookTitle, widget: string}
              - {label: Book Link, name: bookLink, widget: string}
              - {label: Author Name, name: authorName, widget: string}
          - label: Last Good Movie
            name: movie
            widget: list
            fields:
              - {label: Movie Title, name: movieTitle, widget: string}  
              - {label: Movie Link, name: movieLink, widget: string}
          - label: Heavy Rotation      
            name: rotation
            widget: list
            fields:
              - {label: Song Title, name: songTitle, widget: string}
              - {label: Song Link, name: songLink, widget: string}
              - {label: Artist Name, name: artistName, widget: string}

                
     