backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    folder: "/site/content/news/" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Testing", name: "testVariable", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
     