backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - label: "Content Types"
    name: "contentTypes"
    files:
      - label: "News Links"
        name: "newsLinks"
        file: "site/data/news/links.yml"
        fields:
          - {label: Title, name: title, widget: hidden}
          - label: News Item
            name: newsListDisplay
            widget: list
            fields:
              - {label: Article Title, name: news, widget: string}
              - {label: Link, name: link, widget: string}
              - {label: Comment, name: comment, widget: string}
              - {label: Date, name: date, widget: datetime}
      - label: "Affinities Items"
        name: "affinitiesItems"
        file: "site/data/affinities/items.yml"
        fields:
          - {label: Title, name: title, widget: hidden}
          - label: Current Reading 
            name: reading 
            widget: list
            fields:
              - {label: Book Title, name: bookTitle, widget: string}
              - {label: Book Link, name: bookLink, widget: string}
              - {label: Author Name, name: authorName, widget: string}
                
     